### ISSUE TITLE
Count in 'Files open' dialog limited to 1000

### ISSUE THREAD

**Issue by rgieseke** [rgieseke/textredux#10]
When not in recursive mode Textredux should show more than io.SNAPOPEN_MAX (1000) files.

**Comment by loomer** [comment]
I think io.SNAPOPEN_MAX no longer exists does it? 
See: https://foicica.com/hg/textadept/rev/3c16ac279252

**Comment by rgieseke** [comment]
Seems like it, care to submit a PR?

**Comment by rgieseke** [comment]
Fixed in https://github.com/rgieseke/textredux/commit/813fb95b419dab71c789048fd88a1577a30e9558
Thanks again!
