### ISSUE TITLE
Textredux changes line number margins

### ISSUE THREAD

**Issue by jugglerchris** [rgieseke/textredux#13]
Hi,

I'm finding that when opening a textredux buffer, the line number margins on other buffers are being changed.  I think the culprit is set_margin_styles() in core/buffer.lua.

Is there a reason it changes the margin for non-textredux buffers?  In my case (curses) it seems to save the margin width from very early on (before my own INITIALIZED setup code has run), and keeps setting buffers to that width.  Everything seems to work fine if I comment out the second half of the function.

Chris

**Comment by rgieseke** [comment]
I hope this finally fixes it! Let me know if there are any issues.
