### ISSUE TITLE
feature request: open in split 

### ISSUE THREAD

**Issue by jots** [rgieseke/textredux#17]
Would it be possible to have an option for the the functions fs.open_file and textredux.buffer_list.show  to:
- if we only have 1 pane:  split the pane and show the textredux buffer in the other pane (putting focus in there).
- if we already have a split pane:  replace our sibling pane with textredux buffer.

while in textredux buffer:
- when selecting a file or buffer: replace the current textredux buffer with selection (so we are left with 2 panes minimum  { view.split, view, false }).
- if we hit a "1"  while on a file or buffer:  make the current selection take up the entire window. (left with 1 pane: {ui.goto_view, 1, true})

This is similar to how emacs buffer-menu-other-window works, and it is _quite_ handy.

**Comment by rgieseke** [comment]
Sounds quite useful, but I have to think about how (and if) to integrate this with Textredux.
You might like to try something like this:

```Lua
local textredux = require('textredux')
keys.cb = function()
  ui.goto_view(-1, true)
  textredux.buffer_list.show()
end
```

This would just go to the "previous" view but is probably already close to what you have in mind. (Of course possible to extend this to split views etc. if necessary.)
I like how this helps to keep track of where you were when you needed to go to another buffer.

As for the "1" short cut -- by default this would be interpreted as searching for "1". Any other short cut for unsplit all views and go to selected buffer should be easy to add.

**Comment by rgieseke** [comment]
Did you get a change to try this?

**Comment by jots** [comment]
Yes that works well for me, thanks.
Just getting back into textadept after a long hiatus.
Let me see if I can figure out how to bind a key to "unsplit all views and go to selected"

**Comment by rgieseke** [comment]
Let me know (or ping the mailing list) if you need help!
