### ISSUE TITLE
Support For Snapopen in project

### ISSUE THREAD

**Issue by VoltiSubito** [rgieseke/textredux#18]
I've searched around textredux for a bit and was unable to figure out if I could configure textadept to use the textredux snapopen screen when it is in a "project" scope.  

http://foicica.com/textadept/manual.html#Snapopen

**Comment by rgieseke** [comment]
Not sure if I understand the question correctly, but maybe something like

```lua
keys[not OSX and (not CURSES and 'caP' or 'cmp') or 'cmP'] = function()
  local path = io.get_project_root()
  textredux.fs.snapopen(path)
end
```
And then add some code to handle the case when no project root is found ...

**Comment by VoltiSubito** [comment]
That works perfectly.  Thank you!  I was drastically overthinking this and had it in my head that path had to be undefined at the point that io.snapopen was called from snapopen_compat.  I didn't consider calling textredux's snapopen directly :smile: 

By the by.  Thanks a lot for this module.  For some reason I thought, also incorrectly, that textredux was only used for the curses interface.  I just started using it today and wish I had years ago...

**Comment by rgieseke** [comment]
My first thought was as well to look into why this is not hijacked ... It seems to be easily possible by adding a line to use the `get_project_root` function in `snapopen_compat`. I'll test this a bit and likely commit this later.

As for the GUI Textredux. I had long planned to improve the README to be more informative and maybe include a screen shot as in the docs. There is one terminal screenshot in the list of [screenshots](http://rgieseke.github.io/textredux/tour.html). Maybe I should just make this clearer in the text, that it is a text-based interface usable for both curses and GUI version. If you have any other ideas, let me know!

Thanks for your feedback, I'll reopen this to remind me to hopefully fix your issue properly.

**Comment by VoltiSubito** [comment]
In that case, I did the same thing for the USERHOME snapopen and you may wish to add that to the hijack as well.

```lua
keys[not OSX and 'cu' or 'mu'] = function()
  textredux.fs.snapopen(_USERHOME)
end
```

**Comment by rgieseke** [comment]
So, the original problem should be fixed now. Not sure about your last comment, since this would require a different hijacking mechanism, I think.
Or just overwriting the key binding as you suggested (which is what I do as well) ...

**Comment by VoltiSubito** [comment]
Awesome.  Thanks!
