### ISSUE TITLE
No option to change drive on Windows

### ISSUE THREAD

**Issue by thorstenkampe** [rgieseke/textredux#21]
There is no way to switch to another drive on Windows so you're stuck to the current one. See http://foicica.com/lists/code/201512/2827.html

**Comment by rgieseke** [comment]
Thanks for filing an issue! Since Textredux operates on the string of the current path there is no easy way at the moment to get a list of the available drives. I didn't find an easy way to get a list of available drives in Lua. I'll keep you posted when I find something to test :-)

**Comment by rgieseke** [comment]
I found a workaround selection solution (I hope) -- could you test the branch [windows-allow-drive-selection](https://github.com/rgieseke/textredux/tree/windows-allow-drive-selection)

You can pull the branch or grab a zip at https://github.com/rgieseke/textredux/archive/windows-allow-drive-selection.zip

I tested this on Windows 7 with only virtual CD and HD drives, so please let me know if you find any issues. If it works for you I'll merge this into master.

**Comment by thorstenkampe** [comment]
Still nowhere to go at the root:
![image](https://cloud.githubusercontent.com/assets/475462/12378540/09ff1e20-bd41-11e5-89dc-2f95f8f918f6.png)

**Comment by thorstenkampe** [comment]
Ah, `backspace` works. But there should be a visual indicator like `..` that there is something above...

**Comment by rgieseke** [comment]
Good point, I rarely use the ".." so I didn't think of this.

**Comment by rgieseke** [comment]
I've merged this into master. I'll leave this issue open as a reminder to improve the discoverability.

**Comment by snoopy** [comment]
With commit cea8dc764b8888cdc6d935ba3d2d4e9c330d9cff this should be much easier than before.  
Maybe a info message should be added to the open functionality to make users aware of that new feature and then this issue could be closed?

**Comment by rgieseke** [comment]
Something like a status bar message when the path is "C:\"?

**Comment by snoopy** [comment]
I think it would be enough to simply inform users that they can change drives via "/". Or maybe just say they can go to the filesystem root?  
Kind of like the info message when opening the switch buffer list window.

**Comment by rgieseke** [comment]
Sure, that would be helpful. Do you want to create a PR for such a status message?
