### ISSUE TITLE
Cannot create a new file that has a name that matches a subset of an existing file name.

### ISSUE THREAD

**Issue by VoltiSubito** [rgieseke/textredux#24]
+ Create a folder
+ Create a file in the folder called `myfile.txt`
+ Create a new buffer.
+ Using textredux, save the content of the new buffer in the folder created above as `my.txt`

Unless I'm missing something, I think the only option here is to overwrite the existing file.

**Comment by rgieseke** [comment]
Confirmed ... one option, always use native `save as` dialog, another fix the dialog. I think the problem is that the list selection is fixed to the available options.
Workaround, use the menu to get the native `save as`, but this definitely needs to get fixed!

**Comment by rgieseke** [comment]
I've disabled the Textredux `save_as` dialog for now ... might return later ...
