### ISSUE TITLE
small file sorting issue.

### ISSUE THREAD

**Issue by basiliscos** [rgieseke/textredux#25]
Hello!

Thanks for nice plugin!

I have an small enhancement report. When sorting files, the file, with the shortest shared filename should go first, instead of last. I.e.

```
# ls -1 ..
bom                                 # this one goes first
bom-feed
bom-market
bom-platform
bom-postgres
bom-rpc
bom-test
bom-utility
bom-web
bom-websocket-api

```

In the textredux it shows the folders in the order:

```
bom-feed
bom-market
bom-platform
bom-postgres
bom-rpc
bom-test
bom-utility
bom-web
bom-websocket-api
bom                                            # goes last, not nice
```

**Comment by rgieseke** [comment]
Thanks for the report, I'll look into it.

**Comment by rgieseke** [comment]
Hmm, I can't reproduce this using the file open dialog. How are you calling this?

**Comment by basiliscos** [comment]
ctrl+o, which is bounded to 

```lua
keys.co          = textredux.fs.open_file
```

Here is a screenshot http://ctrlv.in/717854

**Comment by rgieseke** [comment]
Ah, it's a problem with the directory sorting (filenames display fine).

**Comment by basiliscos** [comment]
yes

**Comment by rgieseke** [comment]
Want to give this a try?
https://github.com/rgieseke/textredux/blob/master/fs.lua#L242
Maybe first split in directories and files, then sort each? Don't know if there is something more efficient?

**Comment by basiliscos** [comment]
What do you think about https://github.com/rgieseke/textredux/pull/26 ?

**Comment by rgieseke** [comment]
Nice, looks good! I'll merge this when I get back home.
I wonder whether it might also be possible to use a pattern to match `/` at the end of the path to avoid the additional directory check. Anyway, nice solution to remove the '/' without having to sort twice.

**Comment by rgieseke** [comment]
Ah, to fix this on Windows as well we should use `separator` which is defined at the top of the file ...

**Comment by basiliscos** [comment]
Should work on windows too, if the last directory symbol is `\`

**Comment by rgieseke** [comment]
You're right -- I changed it to use string substitution to avoid the extra checking of path type.
Thanks again for the report and solution!
