### ISSUE TITLE
Changing line number background color?

### ISSUE THREAD

**Issue by loomer** [rgieseke/textredux#32]
Any idea which style is responsible for the line number background color when using a list?

**Comment by rgieseke** [comment]
Not sure I understand you correctly, but I hide the line number margin for Textredux buffers (and make another margin the same width to "hide").

https://github.com/rgieseke/textredux/blob/6aff441ea8c8fed8edf1d234ece3b5a51f71717c/core/buffer.lua#L225

The line number style is 33

http://www.scintilla.org/ScintillaDoc.html#StyleDefinition

**Comment by loomer** [comment]
Is this code not in the latest release version? I can't seem to find it there.
Also notice how in this picture (https://rgieseke.github.io/textredux/images/fs_listing.png) the line number margin is still there and has a different color.
Another observation is that if you open the buffer list for the first time the line number margin will have a different color. After you use ctrl+d to close a buffer from the list, the line number margin background color will instantly change to the same color as the edit window background.

I'm just looking for an easy way to consistently change the line number margin bg color in the buffer list.

**Comment by rgieseke** [comment]
> Is this code not in the latest release version? I can't seem to find it there.
Also notice how in this picture (https://rgieseke.github.io/textredux/images/fs_listing.png) the line number margin is still there and has a different color.

Apologies, I searched through the Git logs to find how this was done and ended up linking to an outdated version.
Now it's done just here: 

https://github.com/rgieseke/textredux/blob/aac4349930c1585af5a5f84905113038526bbbf5/core/buffer.lua#L479

The picture is how it is supposed to look.

**Comment by rgieseke** [comment]
Changing the color should work right away, but there might be initialization issues. I think you should be able to change the style as done above:

target.style_back[33] = ...

**Comment by loomer** [comment]
Simply commenting out line 481
https://github.com/rgieseke/textredux/blob/aac4349930c1585af5a5f84905113038526bbbf5/core/buffer.lua#L481
has the desired effect. As this seems to be the easiest solution I'll go with that. Unless there are any horrendous side effects caused by this?

**Comment by rgieseke** [comment]
Absolutely not! If you want you could also keep your changed function in your `init.lua`, overwriting `reduxbuffer._create_target`

**Comment by loomer** [comment]
I'll keep that in mind but for now commenting out the offending line is good enough I think.
Thank you for your quick help on this issue!
