### ISSUE TITLE
feature request : integrate fzf into textredux

### ISSUE THREAD

**Issue by myimages** [rgieseke/textredux#33]
Hi, 

you might have heard of [fzf](https://github.com/junegunn/fzf/). it is an actively developed , general purpose fuzzy finder.

the scoring / matching algorithm is excellent and fast , it would be excellent if this tool could be integrated into textredux as sorter / matcher for results which will do all the heavy lifting and the editor takes care of populating the list and displaying it as it comes from fzf . just like the git ls-files example.

this is where this tool gets integrated into vim [fzf.vim](https://github.com/junegunn/fzf.vim), and the basic idea is that everything is done by the tool and vim just display those results ( with some fine grain control over some fzf settings that could be done over at the editor side if needed ) 

I am still exploring TextAdept myself , and integrating this into TA/Textredux  would be a killer feature, plus it lessen the processing done on the editor / lua side , especially for large repos.

**Comment by rgieseke** [comment]
This is definitely worth investigating! One disadvantage might be that it's probably not super easy to get running on non-Unix platforms. But that's not an argument against having it work like the git ls-files example ...
Want to give it a try?

**Comment by myimages** [comment]
thank you for the reply.

sure ! I ll give it a shot ! 

However , fzf it self does the sorting and the matching as well. so the sorting and matching that is done when `list:show()` gets called is not needed , just like how it is used in vim.

**Comment by rgieseke** [comment]
Maybe that could be overwritten or disabled ... let me know if you have any questions!

**Comment by myimages** [comment]
after looking further into this and some other ways people integrate fzf into their workflow, it seems impossible given that fzf needs a some kind of terminal emulator to work.

**Comment by rgieseke** [comment]
Thanks for the feedback - maybe some kind of messaging setup could work ... or some ideas of fzf be integrated one day.
