### ISSUE TITLE
Snapopen broken with TA 10.5

### ISSUE THREAD

**Issue by loomer** [rgieseke/textredux#50]
It seems the recent TA update to 10.5 broke the snapopen functionality in TR.  
Looking at the [code](https://foicica.com/hg/textadept/rev/5fd6b6d188bf) it's easy to see that the filters no longer match between the two. However that should have broken much earlier than it did.

I don't know if you're already working on a fix so I came up with https://github.com/loomer/textredux/commit/3e626d6556a6ba7bac5e4382b84e2fc4b5009387 which maps the filters to the old ones that TR is using. 

What is your take on this?

**Comment by rgieseke** [comment]
It's probably worth updating to be in line with Textadept, but for me it still works with TA 10.5.
Do you use any special filters?

**Comment by rgieseke** [comment]
Ah, sorry, now i get the error... !

**Comment by rgieseke** [comment]
Care to submit a PR?
