### ISSUE TITLE
reduxstyle missing property?

### ISSUE THREAD

**Issue by loomer** [rgieseke/textredux#52]
The documentation for reduxstyle states the following:
`reduxstyle.list_match_highlight.fore = reduxstyle.class.fore`
However during my tests neither of these had the `fore` property.

I was trying to have TR automatically use the same colors for the file dialogs as in the buffer list. The colors for the buffer list are set in `list.lua`. Hoever the colors for the file dialogs are set in `fs.lua`. The problem here is that they don't work. The file dialogs will not use their assigned colors but instead use the default (text) color.  
Assigning the colors manually via `reduxstyle.list_match_highlight.fore = #123456` does work because you are creating the necessary property.

Is this working as intended or am I maybe missing something?

**Comment by rgieseke** [comment]
You mean styles don't appear as you'd expect them from what's in the code?

like
```lua
--- The style used for ordinary file entries.
reduxstyle.fs_file = reduxstyle.string
```

**Comment by loomer** [comment]
Correct. It works for the buffer list but not for the file related dialogs (open, open home, etc.). These simply use the default text color.  
Does it work for you?

**Comment by rgieseke** [comment]
Yes, in the buffer list and the file open dialog files appear using the string style for me.

**Comment by rgieseke** [comment]
Have you tried with a minimal `init.lua` with only textredux?

**Comment by loomer** [comment]
How are you including TR? I'm only making this call after I set my TA theme:
`require('textredux').hijack()`

**Comment by rgieseke** [comment]
Same:

local textredux = require("textredux")
textredux.hijack()

Are you on 10.6? I haven't updated yet on this box.

**Comment by loomer** [comment]
Yes, I'm on 10.6 but that is not the problem. Apparently the problem is that I'm calling `textredux = require('textredux')` in my `~/.textadept/modules/textadept/keys.lua`. I'm not sure how this interferes but it does. I'll try moving my keybinds back into `init.lua` and see if that fixes it.

**Comment by rgieseke** [comment]
Great, let me know if there still are problems, also about the "fore" property. It could well be that parts of the documentation are out-dated.

As for "keys.lua" -- i think processing keys and menus is done last in "modules/textadept/init.lua".
Maybe this leads to something not being processed in the order required for having the style already set.
