### ISSUE TITLE
Cursor jumps into search area with TA 11.2b2

### ISSUE THREAD

**Issue by snoopy** [rgieseke/textredux#76]
Using TR with TA 11.2 beta 2 the cursor jumps into the user search area when typing text in lists.  
I thought the problem might lie with `list:_refresh()` but changes there do nothing to stop this behavior. Can you check this and see if it is the same for you?

**Comment by rgieseke** [comment]
Yes, I briefly tested the latest beta and stayed on a previous build.
I didn't had time yet to look into the changes in Textadept.

**Comment by rgieseke** [comment]
There have been updates for selection handling and positions as well as an update to latest Scintilla.

**Comment by rgieseke** [comment]
It's the handling of buffer positions in Textadept's history module:

https://github.com/orbitalquark/textadept/blob/1e693f06a6556b87ed4f56a3635a0c10640b1f92/modules/textadept/history.lua

When I add this in Textredux the list seems to work as before, not sure yet if this the best solution:

```lua
events.connect(events.MODIFIED, function()
  if buffer._textredux then return false end
end, 1)
```

**Comment by rgieseke** [comment]
Fixed in main branch.
