### ISSUE TITLE
Textredux fails to load on TA Qt nightly

### ISSUE THREAD

**Issue by snoopy** [rgieseke/textredux#84]
Starting TA with TR and a basic config results in an error: ` ~/.textadept/modules/textredux/init.lua:115: attempt to index a nil value (field '?').`

![trbroken](https://user-images.githubusercontent.com/37296322/209216670-65069c0d-c509-48a3-aa11-44431a6ee77e.png)

**Comment by rgieseke** [comment]
That's odd, works for me. What platform are you on? Linux I assume?
Nothing else in the `.textadept/init.lua`

**Comment by rgieseke** [comment]
Got it ... one of the latest nightlies broke this.

**Comment by rgieseke** [comment]
Should be fixed in https://github.com/rgieseke/textredux/commit/a9a33ab810698a3949c13b2339ddfe8545627da6

**Comment by snoopy** [comment]
Thanks for this simple fix. Guess I didn't see the forest for the trees.
